version: "3.7"

services:
  proxy:
    image: shopify/toxiproxy
    volumes:
      - .:/config
    command: ["--host", "0.0.0.0", "--config", "/config/toxiproxy.json"]

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
    depends_on:
      - proxy
      - redis

  redis:
    image: redis
    depends_on:
      - proxy
